version: "3.9"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://cotex:cotex@postgres:5432/cotex_development
    ports:
      - "80:3000"
    command: npm run start:dev
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app/

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cotex
      POSTGRES_PASSWORD: cotex
      POSTGRES_DB: cotex_development
    volumes:
      - cotex-db:/var/lib/postgresql/data

volumes:
  cotex-db:
